### ISSUE TITLE
Каталог

### ISSUE THREAD

**Issue by wonsarc** [olegSprite/iOS-FakeNFT-StarterProject-Public#77]
- [x] [Модуль 1](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/78) Total: est: 4 h; fact: x h.
- [x] [Модуль 2](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/79) Total: est: 5 h; fact: x h.
- [x] [Модуль 3](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/80) Total: est: 4.5 h; fact: x h.
