### ISSUE TITLE
[M1][Каталог]  Верстка экрана каталога

### ISSUE THREAD

**Issue by wonsarc** [olegSprite/iOS-FakeNFT-StarterProject-Public#78]
- [x] [[Верстка Сортировки] Добавление кнопки сортировки в VC](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/89)
- [x] [[Верстка Сортировки] Добавление алерта для выбора сортировки](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/90)

- [x] [[Верстка Таблицы] Добавление таблицы в VC](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/91)

- [x] [[Верстка Ячейки] Обложка коллекции](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/92)
- [x] [[Верстка Ячейки] Название коллекции](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/93)
- [x] [[Верстка Ячейки] Количество NFT в коллекции](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/94)

Total: est: 4 h; fact: 3.5 h.
