### ISSUE TITLE
[M3][Каталог] Логика

### ISSUE THREAD

**Issue by wonsarc** [olegSprite/iOS-FakeNFT-StarterProject-Public#80]
- [x] [[Экран каталога] Сортировка](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/95)
- [x] [[Экран каталога] Индикатор загрузки](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/96)

- [x] [[Экран коллекции NFT] Добавление/удаление NFT в избранное](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/97)
- [x] [[Экран коллекции NFT] Добавление/удаление NFT в корзину](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/98)

Total: est: 4.5 h; fact: 5.5 h.
