### ISSUE TITLE
[M2][Каталог] Верстка экрана коллекции NFT

### ISSUE THREAD

**Issue by wonsarc** [olegSprite/iOS-FakeNFT-StarterProject-Public#88]
- [x] [[Верстка VC] UIImageView](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/81)
- [x] [[Верстка VC] UILabel](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/82)
- [x] [[Верстка VC] WebView для ссылки](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/83)

- [x] [[Верстка UICollectionView] Добавление UICollectionView в VC](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/84)

- [x] [[Верстка Ячейки] Изображение и Название NFT](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/85)
- [x] [[Верстка Ячейки] Рейтинг и Стоимость NFT](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/86)
- [x] [[Верстка Ячейки] Кнопки сердечка и корзины](https://github.com/olegSprite/iOS-FakeNFT-StarterProject-Public/issues/87)

Total: est: 5 h; fact: 4.5 h.
